dist: trusty
sudo: required
language: node_js
node_js:
- '5'
os:
- linux
env:
  global:
  - DBUS_SESSION_BUS_ADDRESS=/dev/null
  - DISPLAY=:99.0
  - CHROME_BIN=chromium-browser
addons:
  ssh_known_hosts: 138.68.55.159
before_script:
- sh -e /etc/init.d/xvfb start
before_install:
- bash scripts/install.sh
install:
- npm install
script:
- npm run lint
- npm run test:once
- scripts/build.sh
after_success:
- bash scripts/deploy.sh
