dist: trusty
sudo: required
language: node_js
node_js:
- '5'
os:
- linux
env:
  global:
  - DBUS_SESSION_BUS_ADDRESS=/dev/null
  - DISPLAY=:99.0
  - CHROME_BIN=chromium-browser
before_script:
- sh -e /etc/init.d/xvfb start
before_install:
- bash scripts/install.sh
install:
- npm install
script:
- npm run lint
- npm run test:once
- scripts/build.sh
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
